// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEtbsjTlJr2qd1hiLhn6IeCIEBnWwbKvc',
    appId: '1:441359140776:web:cd3e7aae189da9317cbf9d',
    messagingSenderId: '441359140776',
    projectId: 'owneraccount-32f05',
    authDomain: 'owneraccount-32f05.firebaseapp.com',
    storageBucket: 'owneraccount-32f05.appspot.com',
    measurementId: 'G-3R00KRRN78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKq-wFxQ2Bd6lvvKqhNWW-K42gXhoHxmk',
    appId: '1:441359140776:android:2d3bc1f402fd19687cbf9d',
    messagingSenderId: '441359140776',
    projectId: 'owneraccount-32f05',
    storageBucket: 'owneraccount-32f05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsAUAVTGHfKWPzH67x2X8eiKxIPSwDoRU',
    appId: '1:441359140776:ios:508510cf4c77f0337cbf9d',
    messagingSenderId: '441359140776',
    projectId: 'owneraccount-32f05',
    storageBucket: 'owneraccount-32f05.appspot.com',
    iosClientId: '441359140776-led31r9ah00fgcpjqaab6lb9dgkvc1ls.apps.googleusercontent.com',
    iosBundleId: 'com.example.owneaccount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsAUAVTGHfKWPzH67x2X8eiKxIPSwDoRU',
    appId: '1:441359140776:ios:508510cf4c77f0337cbf9d',
    messagingSenderId: '441359140776',
    projectId: 'owneraccount-32f05',
    storageBucket: 'owneraccount-32f05.appspot.com',
    iosClientId: '441359140776-led31r9ah00fgcpjqaab6lb9dgkvc1ls.apps.googleusercontent.com',
    iosBundleId: 'com.example.owneaccount',
  );
}
